services:
  - type: web
    name: viji-marimony-deploy-backend
    region: mumbai
    buildCommand: npm install && cd backend && npm install && npx prisma generate
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000